language: c

os: linux
compiler: gcc

git:
  submodules: false

env:
  matrix:
    - UPGRADE_FROM=0.3.0
    - UPGRADE_FROM=0.2.2
    - UPGRADE_FROM=0.2.0
    - UPGRADE_FROM=0.1.0
    - GIT_VERSION=2.7.4 UPGRADE_FROM=0.2.2
    - MERCURIAL_VERSION=3.0
    - MERCURIAL_VERSION=3.6

matrix:
  include:
    - os: osx
      compiler: clang
      # Without an env, it ends up with all the env variables from the matrix
      # (so, in practice, the last value of each)
      env:
      - VARIANT=
      - GIT_CINNABAR_EXPERIMENTS=true
    - os: osx
      compiler: clang
      osx_image: xcode7
      env:
      - VARIANT=asan
      - GIT_CINNABAR_EXPERIMENTS=true
    - os: linux
      compiler: gcc
      env:
      - VARIANT=
      - GIT_CINNABAR_EXPERIMENTS=true
    - os: linux
      compiler: gcc-4.8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.8
        artifacts:
          paths: artifacts
          target_paths: /artifacts
      env:
      - VARIANT=asan
      - GIT_CINNABAR_EXPERIMENTS=true

addons:
  artifacts:
    paths: artifacts
    target_paths: /artifacts

before_install:
  - make -f CI.mk before_install

before_script:
  - make -f CI.mk before_script

script:
  - make -f CI.mk script
  - make -f CI.mk script NO_BUNDLE2=1 UPGRADE_FROM=
