language: c

os: linux
compiler: gcc

cache:
- ccache
- directories:
  - $HOME/.cache/pip
  - $HOME/Library/Caches/pip

git:
  submodules: false

matrix:
  include:
    - language: python
      python: "2.7"
      env: PYTHON_CHECKS=1
    - os: osx
      compiler: clang
      # Without an env, it ends up with all the env variables from the matrix
      # (so, in practice, the last value of each)
      env:
      - VARIANT=
      - GIT_CINNABAR_EXPERIMENTS=true
    - os: osx
      compiler: clang
      osx_image: xcode7
      env:
      - VARIANT=asan
      - GIT_CINNABAR_EXPERIMENTS=true
    - os: linux
      compiler: gcc
      env:
      - VARIANT=
      - GIT_CINNABAR_EXPERIMENTS=true
    - os: linux
      compiler: gcc-4.8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.8
        artifacts:
          paths: artifacts
          target_paths: /artifacts
      env:
      - VARIANT=asan
      - GIT_CINNABAR_EXPERIMENTS=true
    - env: GIT_CINNABAR_HELPER=""
    - env: UPGRADE_FROM=0.3.0
    - env: UPGRADE_FROM=0.2.2
    - env: UPGRADE_FROM=0.2.0
    - env: UPGRADE_FROM=0.1.0
    - env:
      - GIT_VERSION=2.7.4
      - UPGRADE_FROM=0.2.2
    - env: GIT_VERSION=2.5.0
    - env: GIT_VERSION=2.2.0
    - env: GIT_VERSION=2.0.0
    - env: GIT_VERSION=1.8.5
    - env: MERCURIAL_VERSION=3.0
    - env: MERCURIAL_VERSION=3.6
  # Workaround for https://github.com/travis-ci/travis-ci/issues/4681
  exclude:
    - os: linux
    - compiler: gcc

addons:
  artifacts:
    paths: artifacts
    target_paths: /artifacts

before_install:
  - make -f CI.mk before_install

before_script:
  - make -f CI.mk before_script

script:
  - make -f CI.mk script
  - make -f CI.mk script NO_BUNDLE2=1 UPGRADE_FROM=
